[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "minemind"
version = "0.1.0"

[project.scripts]
# 'minemind' command calls the main function inside minemind/cli.py
minemind = "minemind.cli:main"